import { FIELD_CATALOGUE, type FieldDef } from './field-catalogue';
import { REGISTRY_CLINICAL_MODELS, parseRegistrySchema, registryOnlyReason, type RegistryField } from './registry-schema';
import { SCHEMA_VERSION } from '../store/database';

const METHOD_LABEL: Record<FieldDef['method'], string> = {
  EXTRACT: 'Deterministic text rule',
  CALCULATE: 'Calculation module',
  STRUCTURAL: 'Entity structure / metadata',
  MANUAL: 'Manual entry',
};

function cell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function sourcesOf(defs: FieldDef[]): string {
  const all = [...new Set(defs.flatMap((d) => d.sources))];
  return all.length ? all.join(', ') : '—';
}

export interface MappingSummary {
  registryFields: number;
  fedByExtractor: number;
  registryOnly: number;
  unaccounted: RegistryField[];
  gapFields: FieldDef[];
}

export function summariseMapping(registry: RegistryField[] = parseRegistrySchema()): MappingSummary {
  const inScope = registry.filter((f) => (REGISTRY_CLINICAL_MODELS as readonly string[]).includes(f.model));
  let fed = 0;
  let only = 0;
  const unaccounted: RegistryField[] = [];
  for (const f of inScope) {
    const target = `${f.model}.${f.field}`;
    if (FIELD_CATALOGUE.some((d) => d.registryTargets.includes(target))) fed++;
    else if (registryOnlyReason(f.model, f.field)) only++;
    else unaccounted.push(f);
  }
  return {
    registryFields: inScope.length,
    fedByExtractor: fed,
    registryOnly: only,
    unaccounted,
    gapFields: FIELD_CATALOGUE.filter((d) => d.registryTargets.length === 0),
  };
}

export function renderFieldMapping(registry: RegistryField[] = parseRegistrySchema()): string {
  const inScope = registry.filter((f) => (REGISTRY_CLINICAL_MODELS as readonly string[]).includes(f.model));
  const summary = summariseMapping(registry);
  const out: string[] = [];
  out.push('# Registry Field Mapping — SIRT Patient Episode Extractor');
  out.push('');
  out.push('> GENERATED by `apps/extractor/scripts/generate-field-mapping.ts` from `src/domain/field-catalogue.ts` and `apps/api/prisma/schema.prisma`. Do not edit by hand — edit the catalogue and regenerate. `registry-mapping.spec.ts` fails if any registry field is unaccounted for.');
  out.push('');
  out.push(`Extractor store schema version: ${SCHEMA_VERSION}.`);
  out.push('');
  out.push('Conventions: **AI-derived** is always "No" — AI output is never an authoritative registry value (it may only be offered as a suggestion that a clinician must verify). **Verification**: ALWAYS = every value verified before push; LOW_CONFIDENCE = verify if confidence < 0.85, OCR-derived, or conflicting; ON_CONFLICT = verify only when sources disagree. Required = counted by the completeness engine.');
  out.push('');
  out.push(`Summary: ${summary.registryFields} registry columns in scope; ${summary.fedByExtractor} fed by the extractor; ${summary.registryOnly} registry-only (system / workflow / identifiable / clinician-decision / formula-not-adopted); ${summary.unaccounted.length} unaccounted. ${summary.gapFields.length} extractor fields have **no registry home** (see §2).`);
  out.push('');
  out.push('## 1. Every registry field');
  out.push('');
  out.push('| Registry field | Extractor entity.field | Source document type | Extraction method | Formula | AI-derived | Required | Verification |');
  out.push('|---|---|---|---|---|---|---|---|');
  for (const f of inScope) {
    const target = `${f.model}.${f.field}`;
    const defs = FIELD_CATALOGUE.filter((d) => d.registryTargets.includes(target));
    if (defs.length > 0) {
      out.push(
        `| \`${target}\` | ${defs.map((d) => `\`${d.entity}.${d.key}\``).join('<br>')} | ${sourcesOf(defs)} | ${[...new Set(defs.map((d) => METHOD_LABEL[d.method]))].join(' / ')} | ${defs.map((d) => d.formulaId).filter(Boolean).join(', ') || '—'} | No | ${defs.some((d) => d.required) ? 'Required' : 'Optional'} | ${[...new Set(defs.map((d) => d.verification))].join(' / ')} |`,
      );
    } else {
      const ro = registryOnlyReason(f.model, f.field);
      out.push(`| \`${target}\` | — (registry-only: ${ro ? ro.reason : '**UNACCOUNTED**'}) | — | — | — | No | — | ${cell(ro ? ro.note : 'UNACCOUNTED')} |`);
    }
  }
  out.push('');
  out.push('## 2. Extractor fields with no registry home (schema gaps)');
  out.push('');
  out.push('These are captured, provenance-tracked and exportable from the extractor, but cannot be pushed into the current registry without an additive registry migration (Phase 5 proposal). Nothing is dropped silently.');
  out.push('');
  out.push('| Extractor entity.field | Label | Unit | Source document type | Method | Formula | Required | Verification | Note |');
  out.push('|---|---|---|---|---|---|---|---|---|');
  for (const d of summary.gapFields) {
    out.push(`| \`${d.entity}.${d.key}\` | ${cell(d.label)} | ${d.unit ?? '—'} | ${d.sources.join(', ') || '—'} | ${METHOD_LABEL[d.method]} | ${d.formulaId ?? '—'} | ${d.required ? 'Required' : 'Optional'} | ${d.verification} | ${cell(d.note ?? '')} |`);
  }
  out.push('');
  out.push('## 3. Field notes (all catalogue entries with a note)');
  out.push('');
  for (const d of FIELD_CATALOGUE.filter((x) => x.note && x.registryTargets.length > 0)) {
    out.push(`- \`${d.entity}.${d.key}\` → ${d.registryTargets.map((t) => `\`${t}\``).join(', ')}: ${d.note}`);
  }
  out.push('');
  out.push('## 4. Special fields requested in the brief');
  out.push('');
  out.push('| Field | Present in current registry? | Extractor handling |');
  out.push('|---|---|---|');
  out.push('| MELD | Yes (`calculatedMeld3Score`, `calculatedMeldNaScore`) | MELD 3.0 via strict wrapper; MELD-Na **not populated** (legacy double-sodium defect). |');
  out.push('| Child-Pugh | Yes (calculated + confirmed) | Strict 5/5-component calculation; documented class → confirmed after verification. |');
  out.push('| ALBI | Yes | Calculated from verified bilirubin + albumin. |');
  out.push('| TNM | Yes (calculated + confirmed T/N/M) | Documented TNM only → confirmed*; no TNM calculator. |');
  out.push('| Sarcopenia | **No** | Captured if documented; gap. |');
  out.push('| Neutrophils | **No** | Captured; gap. |');
  out.push('| ALT / AST / ALP | **No** | Captured; gap. |');
  out.push('| Pathology | Partial (`histologyConfirmed` only) | Histology, grade, Ki-67 captured; gap. |');
  out.push('| Source outcome | Partial (`EpisodeOutcome`) | Outcome fields carry full provenance in extractor. |');
  out.push('| Per-lesion response | Partial (`FollowUp.lesionId` + `overallResponse` text) | Lesion-level serial measurements + RECIST/mRECIST with inputs; dimensions are a gap. |');
  out.push('| CBCT A/T ratio | **No** in Prisma; **Yes** in V116 (`cbctAtRatio`) | Angiosome-to-tumour volume ratio: CBCT perfused ÷ CBCT tumour volume. Documented + calculated. |');
  out.push('| MAA A/T ratio | **No** in Prisma; **Yes** in V116 (`maaAtRatio`) | MAA perfused ÷ MAA tumour volume, no cross-source fallback. Distinct from T/N uptake ratio (`tumourNormalRatio`). |');
  out.push('');
  return out.join('\n');
}
